# Generated by Django 4.2 on 2024-05-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текст')),
                ('image', models.ImageField(blank=True, default='static/blog.jpg', null=True, upload_to='blog/', verbose_name='изображение')),
                ('count_of_view', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
            ],
        ),
    ]
