# Generated by Django 4.2 on 2024-05-06 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mailing_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mail_service.mailing', verbose_name='Рассылка'),
            preserve_default=False,
        ),
    ]
