# Generated by Django 4.2 on 2024-05-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0002_message_mailing_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(choices=[('minutely', 'Ежеминутно'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=20, verbose_name='Периодичность'),
        ),
    ]
