# Generated by Django 4.2 on 2024-05-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0003_alter_mailing_frequency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryAttempt',
            new_name='Log',
        ),
    ]
