# Generated by Django 4.2 on 2024-05-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0006_mailing_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='message',
        ),
    ]
