# Generated by Django 4.2 on 2024-05-22 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0007_remove_mailing_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('change_status', 'Can change status')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
